AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Step Up! - Episode 7 - Build a Text Adventure Game with AWS Step Functions

Globals:
  Function:
      Timeout: 60
      Tracing: Active

Resources:
  #State Machines
  GameEngine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: code/statemachines/game_engine.asl.json
      DefinitionSubstitutions:
        GameTitle: "Stranded"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameStateDB

  #Functions
  GameEngineInputProxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "GameEngineInputProxy"
      Runtime: "python3.9"
      CodeUri: "code/functions/game_engine_input_proxy"
      Handler: "game_engine_input_proxy.lambda_handler"
      Environment:
        Variables:
          GAME_ENGINE_ARN: !GetAtt GameEngine.Arn
          GAME_STATE_TABLE_NAME: !Ref GameStateDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameStateDB
        - Statement:
          - Sid: AWSStepFunctionsAccess
            Effect: Allow
            Action:
            - states:*
            Resource: "*"

  #Databases
  GameStateDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: GameState
      PrimaryKey: {"Name": "id", "Type": "String"}


