AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Step Up! - Episode 7 - Build a Text Adventure Game with AWS Step Functions

Globals:
  Function:
      Timeout: 60
      Tracing: Active

Resources:
  #State Machines
  GameEngine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: code/statemachines/game_engine.asl.json
      DefinitionSubstitutions:
        GameTitle: "Stranded"
        GameStateTableName: !Ref GameStateDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameStateDB

  #Functions
  GameEngineProxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "GameEngineProxy"
      Runtime: "python3.9"
      CodeUri: "code/functions/game_engine_proxy"
      Handler: "game_engine_proxy.lambda_handler"
      Environment:
        Variables:
          GAME_ENGINE_ARN: !GetAtt GameEngine.Arn
          GAME_STATE_TABLE_NAME: !Ref GameStateDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameStateDB
        - Statement:
          - Sid: AWSStepFunctionsAccess
            Effect: Allow
            Action:
            - states:*
            Resource: "*"

  #Databases
  GameStateDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StepUp-Episode7-GameState
      AttributeDefinitions:
        - 
          AttributeName: "username"
          AttributeType: "S"
        - 
          AttributeName: "gameId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "username"
          KeyType: "HASH"
        - 
          AttributeName: "gameId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


